<?php

/**
 * BaseInvite
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $code
 * @property integer $generater_id
 * @property string $purpose
 * @property boolean $is_used
 * @property integer $used_by
 * @property date $expire_date
 * 
 * @method string  getCode()         Returns the current record's "code" value
 * @method integer getGeneraterId()  Returns the current record's "generater_id" value
 * @method string  getPurpose()      Returns the current record's "purpose" value
 * @method boolean getIsUsed()       Returns the current record's "is_used" value
 * @method integer getUsedBy()       Returns the current record's "used_by" value
 * @method date    getExpireDate()   Returns the current record's "expire_date" value
 * @method Invite  setCode()         Sets the current record's "code" value
 * @method Invite  setGeneraterId()  Sets the current record's "generater_id" value
 * @method Invite  setPurpose()      Sets the current record's "purpose" value
 * @method Invite  setIsUsed()       Sets the current record's "is_used" value
 * @method Invite  setUsedBy()       Sets the current record's "used_by" value
 * @method Invite  setExpireDate()   Sets the current record's "expire_date" value
 * 
 * @package    Sirius
 * @subpackage model
 * @author     Cary Yang <getcary@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInvite extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('invite');
        $this->hasColumn('code', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '100',
             ));
        $this->hasColumn('generater_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('purpose', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'register',
             'length' => '100',
             ));
        $this->hasColumn('is_used', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('used_by', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('expire_date', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}