<?php

/**
 * BaseMonitorProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $target_name
 * @property string $target_type
 * @property integer $profile_id
 * 
 * @method string         getTargetName()  Returns the current record's "target_name" value
 * @method string         getTargetType()  Returns the current record's "target_type" value
 * @method integer        getProfileId()   Returns the current record's "profile_id" value
 * @method MonitorProfile setTargetName()  Sets the current record's "target_name" value
 * @method MonitorProfile setTargetType()  Sets the current record's "target_type" value
 * @method MonitorProfile setProfileId()   Sets the current record's "profile_id" value
 * 
 * @package    Sirius
 * @subpackage model
 * @author     Cary Yang <getcary@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMonitorProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('monitor_profile');
        $this->hasColumn('target_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '255',
             ));
        $this->hasColumn('target_type', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('profile_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}