<?php

/**
 * BaseReportDailyFollowerCount
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $profile_name
 * @property string $profile_type
 * @property date $date
 * @property integer $count
 * 
 * @method integer                  getProfileName()  Returns the current record's "profile_name" value
 * @method string                   getProfileType()  Returns the current record's "profile_type" value
 * @method date                     getDate()         Returns the current record's "date" value
 * @method integer                  getCount()        Returns the current record's "count" value
 * @method ReportDailyFollowerCount setProfileName()  Sets the current record's "profile_name" value
 * @method ReportDailyFollowerCount setProfileType()  Sets the current record's "profile_type" value
 * @method ReportDailyFollowerCount setDate()         Sets the current record's "date" value
 * @method ReportDailyFollowerCount setCount()        Sets the current record's "count" value
 * 
 * @package    Sirius
 * @subpackage model
 * @author     Cary Yang <getcary@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseReportDailyFollowerCount extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('report_daily_follower_count');
        $this->hasColumn('profile_name', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('profile_type', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('date', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
        $this->hasColumn('count', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));


        $this->index('profile_index', array(
             'fields' => 
             array(
              0 => 'profile_name',
              1 => 'profile_type',
             ),
             ));
        $this->index('profile_date_index', array(
             'fields' => 
             array(
              0 => 'profile_name',
              1 => 'profile_type',
              2 => 'date',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}