<?php

/**
 * TabsSettings
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Sirius
 * @subpackage model
 * @author     Cary Yang <getcary@gmail.com>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class TabsSettings extends BaseTabsSettings
{

}