<?php

/**
 * Thread
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Sirius
 * @subpackage model
 * @author     Cary Yang
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Thread extends BaseThread
{

}