ReportDailyCount:
  actAs:
    Timestampable:
  columns:
    profile_name:	{ type: string(255), notnull: true }
    profile_type:	{ type: string(255), notnull: true }
    date:			{ type: date, notnull: false }
    followers_count: { type: integer, notnull: false }
    friends_count:	{ type: integer, notnull: false }
    statuses_count:	{ type: integer, notnull: false }
  indexes:
    profile_index:	{ fields: [profile_name, profile_type] }
    profile_date_index:	{ fields: [profile_name, profile_type, date], type: unique }

MonitorProfile:
  actAs:
    Timestampable:
  columns:
    target_name:	{ type: string(255), notnull: false }
    target_type:	{ type: string(255), notnull: true }
    profile_id:		{ type: integer, notnull: false }

